import './globals.css'
import type { Metadata } from 'next'
import { Patrick_Hand } from 'next/font/google'
import Nav from '../components/nav';


const paddy = Patrick_Hand({ weight: '400',
subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={paddy.className}>
        <Nav />

        {children}

        </body>
    </html>
  )
}
